In [11]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [12]:
data = pd.read_csv("/kaggle/input/competitions/digit-recognizer/train.csv")
data = np.array(data) #converting pandadataframes to array to compute
r, c = data.shape
np.random.shuffle(data) #shuffeling the data set to prevent overfitting

In [21]:
data_ = data[0:1000] #developemnt and validation set
data_ = data_.T #transpose the matrix (m.n - n.m)
print(data_)
Y_dev = data_[0] # getting lables
X_dev = data_[1:c] #taking activation of all the pixels 

[[7 9 8 ... 3 3 2]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [14]:
data_Train = data[1000:r].T 
Y_Train = data_Train[0] #getting lables
X_Train = data_Train[1:c] #taking actiavtion of all pixels

In [15]:
def init_Para():
    #for 1st layer
    W1 = np.random.rand(10, 784) #10 rows and 784 col having 784 weights for each rows (neurons) i.e 10
    b1 = np.random.rand(10, 1) #10 rows with 1 col having 1 bias for each rows (neurons)
    #for 2nd layer 
    W2 = np.random.rand(10, 10)
    b2 = np.random.rand(10, 1)
    return W1,b1,W2,b2

In [16]:
def sigmoid(Zi): #activation function
    return 1 / (1 + np.exp(-Zi))

In [17]:
def softmax(Zi):
    return exp(Zi)/np.sum(exp(Zi))

In [18]:
def forward_pass(W1,b1,W2,b2,X):
    Z1 = W1.dot(X) + b1
    A1 = sigmoid(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(A1)
    return Z1,A1,Z2,A2

In [46]:
print(Y_Train.size)


41000


In [44]:
def onehot(number_of_lables,number_of_neurons=10):
    n = number_of_lables.shape[0]
    Output_matrix = np.zeros((n, number_of_neurons))
    for x,i in enumerate(number_of_lables):
        Output_matrix[x][i] = 1
    return Output_matrix.astype(int)
        
    

In [45]:
a = Y_Train
onehot(a)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], shape=(41000, 10))

In [ ]:
def Backprop_single(Z1,A1,Z2,A2,W2,Y, X):
    loss = (Y-A2) ** 2 #correct out put - predecited for each neuron
#-----FOR OUTPUT LAYER--------
    #Chain rule
    dC_da2 = 2(A2-Y) #d of loss wrt to previous activation
    da_dz2 = A2 * (1 - A2) #d of loss wrt to prvious weightsum
    dz_dw2 = A1 #d of loss wrt to previous weight
    dc_dw2 = dc_da2 * da_dz2 * dz_dw #gradient of w2 #change in loss(cost) of each neuron wrt to its change it weight
    dc_dw2 = dc_da2 * da_dz2 * 1 #gradient of w2 #change in loss(cost) of each neuron wrt to its change it bias

#passing error in hidden layer
    dC_da1 = dc_da2 * da_dz2 * w2

    
#-----FOR HIDDEN LAYER--------
    #Chain rule
    dC_da1 = 2(A1-Y) #d of loss wrt to previous activation
    da_dz1 = A1 * (1 - A1) #d of loss wrt to prvious weightsum
    dz_dw1 = X #d of loss wrt to previous weight
    dc_dw1 = dc_da * da_dz1 * dz_dw #gradient of w1 #change in loss(cost) of each neuron wrt to its change it weight
    dc_dw1 = dc_da * da_dz1 * 1  #gradient of w1 #change in loss(cost) of each neuron wrt to its change it bias
   